# Generated by Django 3.0.2 on 2020-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_module', '0003_auto_20200301_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='about',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='skills',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='web_url',
            field=models.TextField(max_length=80),
        ),
    ]
